[package]
name = "pinyin_tone_marks"
version = "0.1.0"
authors = ["Chris Dunphy <chris@megaparsec.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
log = "0.4.8"

log4rs = "0.12.0"