name: pinyin_tone_marks CI/CD
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [closed]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  push_to_registry:
    name: Push Docker image to GitHub Packages
    needs: build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get the app version
        run: echo "APP_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: atomicmeganerd/pinyin_tone_marks/pinyin_tone_marks
          tags: ${{ env.APP_VERSION }},latest
